name: pub_api_client
description: An API Client for Pub to interact with public package information.
version: 2.6.0
homepage: https://github.com/leoafarias/pub_api_client

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.2
  http: ^1.1.0
  oauth2: ^2.0.2
  path: ^1.8.3
  pubspec: ^2.3.0

dev_dependencies:
  build_runner: ^2.4.6
  build_version: ^2.1.1
  lints: ^2.1.1
  test: ^1.24.4
  test_cov: ^1.0.1
