name: pub_api_client
description: An API Client for Pub to interact with public package information.
version: 3.2.0
homepage: https://github.com/leoafarias/pub_api_client

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  
  dart_mappable: ^4.2.2
  http: ^1.1.0
  oauth2: ^2.0.2
  path: ^1.8.3
  pubspec_parse: ^1.3.0

dev_dependencies:
  build_runner: ^2.4.8
  build_version: ^2.1.1
  dart_mappable_builder: ^4.2.3
  lints: ^2.1.1
  test: ^1.24.4
  test_cov: ^1.0.1
