name: pub_api_client
description: An API Client for Pub to interact with public package information.
version: 1.0.9-dev
homepage: https://github.com/leoafarias/pub_api_client

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  freezed_annotation: ^0.12.0
  http: ^0.12.2
  json_annotation: ^3.1.0
  meta: ^1.2.3
  pub_semver: ^1.4.4
  pubspec_parse: ^0.1.5

dev_dependencies:
  build_runner: ^1.10.3
  build_version: ^2.0.1
  freezed: ^0.12.2
  json_serializable: ^3.5.0
  pedantic: ^1.9.2
  remove_from_coverage: ^1.0.7
  test: ^1.15.4
  test_coverage: ^0.4.3
